version: '3.8'
services:
  db:
    image: postgres:latest
    container_name: inventory_container
    environment:
      POSTGRES_DB: "inventory_db"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5433:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data: